<?php
/**
 * OutputTypeV1TOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TruEdit REST API
 *
 * Welcome to the TruEdit Platform REST API Reference! You can use this REST API to develop integrations between TruEdit and other applications or script interactions with TruEdit.
 *
 * OpenAPI spec version: 1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OutputTypeV1TOTest Class Doc Comment
 *
 * @category    Class */
// * @description OutputTypeV1TO
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OutputTypeV1TOTest extends \PHPUnit_Framework_TestCase {


	/**
	 * Setup before running any test case
	 */
	public static function setUpBeforeClass() {
	}

	/**
	 * Setup before running each test case
	 */
	public function setUp() {
	}

	/**
	 * Clean up after running each test case
	 */
	public function tearDown() {
	}

	/**
	 * Clean up after running all test cases
	 */
	public static function tearDownAfterClass() {
	}

	/**
	 * Test "OutputTypeV1TO"
	 */
	public function testOutputTypeV1TO() {
	}

	/**
	 * Test attribute "config"
	 */
	public function testPropertyConfig() {
	}

	/**
	 * Test attribute "gen_on_save_revision"
	 */
	public function testPropertyGenOnSaveRevision() {
	}

	/**
	 * Test attribute "id"
	 */
	public function testPropertyId() {
	}

	/**
	 * Test attribute "is_system"
	 */
	public function testPropertyIsSystem() {
	}

	/**
	 * Test attribute "modified"
	 */
	public function testPropertyModified() {
	}

	/**
	 * Test attribute "name"
	 */
	public function testPropertyName() {
	}

	/**
	 * Test attribute "suffix"
	 */
	public function testPropertySuffix() {
	}
}
