<?php
/**
 * TargetMediaV1TOTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TruEdit REST API
 *
 * Welcome to the TruEdit Platform REST API Reference! You can use this REST API to develop integrations between TruEdit and other applications or script interactions with TruEdit.
 *
 * OpenAPI spec version: 1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TargetMediaV1TOTest Class Doc Comment
 *
 * @category    Class */
// * @description TargetMediaV1TO
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TargetMediaV1TOTest extends \PHPUnit_Framework_TestCase {


	/**
	 * Setup before running any test case
	 */
	public static function setUpBeforeClass() {
	}

	/**
	 * Setup before running each test case
	 */
	public function setUp() {
	}

	/**
	 * Clean up after running each test case
	 */
	public function tearDown() {
	}

	/**
	 * Clean up after running all test cases
	 */
	public static function tearDownAfterClass() {
	}

	/**
	 * Test "TargetMediaV1TO"
	 */
	public function testTargetMediaV1TO() {
	}

	/**
	 * Test attribute "height"
	 */
	public function testPropertyHeight() {
	}

	/**
	 * Test attribute "id"
	 */
	public function testPropertyId() {
	}

	/**
	 * Test attribute "intent"
	 */
	public function testPropertyIntent() {
	}

	/**
	 * Test attribute "name"
	 */
	public function testPropertyName() {
	}

	/**
	 * Test attribute "orientation"
	 */
	public function testPropertyOrientation() {
	}

	/**
	 * Test attribute "units"
	 */
	public function testPropertyUnits() {
	}

	/**
	 * Test attribute "width"
	 */
	public function testPropertyWidth() {
	}
}
