<?php
/**
 * AppliedStatusV1TO
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TruEdit REST API
 *
 * Welcome to the TruEdit Platform REST API Reference! You can use this REST API to develop integrations between TruEdit and other applications or script interactions with TruEdit.
 *
 * OpenAPI spec version: 1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * AppliedStatusV1TO Class Doc Comment
 *
 * @category Class
 * @description Describes an Applied Status in a TruEdit Workflow, i.e. one step.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AppliedStatusV1TO implements ModelInterface, ArrayAccess {

	const DISCRIMINATOR = null;

	/**
	  * The original name of the model.
	  *
	  * @var string
	  */
	protected static $swaggerModelName = 'AppliedStatusV1TO';

	/**
	  * Array of property to type mappings. Used for (de)serialization
	  *
	  * @var string[]
	  */
	protected static $swaggerTypes = [
		'after_status' => 'int',
		'description'  => 'string',
		'id'           => 'int',
		'name'         => 'string',
		'order'        => 'int',
		'transitions'  => '\Swagger\Client\Model\TransitionV1TO[]',
	];

	/**
	  * Array of property to format mappings. Used for (de)serialization
	  *
	  * @var string[]
	  */
	protected static $swaggerFormats = [
		'after_status' => 'int64',
		'description'  => null,
		'id'           => 'int64',
		'name'         => null,
		'order'        => 'int32',
		'transitions'  => null,
	];

	/**
	 * Array of property to type mappings. Used for (de)serialization
	 *
	 * @return array
	 */
	public static function swaggerTypes() {
		return self::$swaggerTypes;
	}

	/**
	 * Array of property to format mappings. Used for (de)serialization
	 *
	 * @return array
	 */
	public static function swaggerFormats() {
		return self::$swaggerFormats;
	}

	/**
	 * Array of attributes where the key is the local name,
	 * and the value is the original name
	 *
	 * @var string[]
	 */
	protected static $attributeMap = [
		'after_status' => 'afterStatus',
		'description'  => 'description',
		'id'           => 'id',
		'name'         => 'name',
		'order'        => 'order',
		'transitions'  => 'transitions',
	];

	/**
	 * Array of attributes to setter functions (for deserialization of responses)
	 *
	 * @var string[]
	 */
	protected static $setters = [
		'after_status' => 'setAfterStatus',
		'description'  => 'setDescription',
		'id'           => 'setId',
		'name'         => 'setName',
		'order'        => 'setOrder',
		'transitions'  => 'setTransitions',
	];

	/**
	 * Array of attributes to getter functions (for serialization of requests)
	 *
	 * @var string[]
	 */
	protected static $getters = [
		'after_status' => 'getAfterStatus',
		'description'  => 'getDescription',
		'id'           => 'getId',
		'name'         => 'getName',
		'order'        => 'getOrder',
		'transitions'  => 'getTransitions',
	];

	/**
	 * Array of attributes where the key is the local name,
	 * and the value is the original name
	 *
	 * @return array
	 */
	public static function attributeMap() {
		return self::$attributeMap;
	}

	/**
	 * Array of attributes to setter functions (for deserialization of responses)
	 *
	 * @return array
	 */
	public static function setters() {
		return self::$setters;
	}

	/**
	 * Array of attributes to getter functions (for serialization of requests)
	 *
	 * @return array
	 */
	public static function getters() {
		return self::$getters;
	}

	/**
	 * The original name of the model.
	 *
	 * @return string
	 */
	public function getModelName() {
		return self::$swaggerModelName;
	}





	/**
	 * Associative array for storing property values
	 *
	 * @var mixed[]
	 */
	protected $container = [];

	/**
	 * Constructor
	 *
	 * @param mixed[] $data Associated array of property values
	 *                      initializing the model
	 */
	public function __construct( array $data = null ) {
		$this->container['after_status'] = isset( $data['after_status'] ) ? $data['after_status'] : null;
		$this->container['description']  = isset( $data['description'] ) ? $data['description'] : null;
		$this->container['id']           = isset( $data['id'] ) ? $data['id'] : null;
		$this->container['name']         = isset( $data['name'] ) ? $data['name'] : null;
		$this->container['order']        = isset( $data['order'] ) ? $data['order'] : null;
		$this->container['transitions']  = isset( $data['transitions'] ) ? $data['transitions'] : null;
	}

	/**
	 * Show all the invalid properties with reasons.
	 *
	 * @return array invalid properties with reasons
	 */
	public function listInvalidProperties() {
		$invalidProperties = [];

		return $invalidProperties;
	}

	/**
	 * Validate all the properties in the model
	 * return true if all passed
	 *
	 * @return bool True if all properties are valid
	 */
	public function valid() {

		return true;
	}


	/**
	 * Gets after_status
	 *
	 * @return int
	 */
	public function getAfterStatus() {
		return $this->container['after_status'];
	}

	/**
	 * Sets after_status
	 *
	 * @param int $after_status the ID of the Status whose Applied Status in this Workflow an Applied Status being created should come after, or 0 for the beginning. Input only, and only used during creation and update.
	 *
	 * @return $this
	 */
	public function setAfterStatus( $after_status ) {
		$this->container['after_status'] = $after_status;

		return $this;
	}

	/**
	 * Gets description
	 *
	 * @return string
	 */
	public function getDescription() {
		return $this->container['description'];
	}

	/**
	 * Sets description
	 *
	 * @param string $description description
	 *
	 * @return $this
	 */
	public function setDescription( $description ) {
		$this->container['description'] = $description;

		return $this;
	}

	/**
	 * Gets id
	 *
	 * @return int
	 */
	public function getId() {
		return $this->container['id'];
	}

	/**
	 * Sets id
	 *
	 * @param int $id id
	 *
	 * @return $this
	 */
	public function setId( $id ) {
		$this->container['id'] = $id;

		return $this;
	}

	/**
	 * Gets name
	 *
	 * @return string
	 */
	public function getName() {
		return $this->container['name'];
	}

	/**
	 * Sets name
	 *
	 * @param string $name name
	 *
	 * @return $this
	 */
	public function setName( $name ) {
		$this->container['name'] = $name;

		return $this;
	}

	/**
	 * Gets order
	 *
	 * @return int
	 */
	public function getOrder() {
		return $this->container['order'];
	}

	/**
	 * Sets order
	 *
	 * @param int $order order
	 *
	 * @return $this
	 */
	public function setOrder( $order ) {
		$this->container['order'] = $order;

		return $this;
	}

	/**
	 * Gets transitions
	 *
	 * @return \Swagger\Client\Model\TransitionV1TO[]
	 */
	public function getTransitions() {
		return $this->container['transitions'];
	}

	/**
	 * Sets transitions
	 *
	 * @param \Swagger\Client\Model\TransitionV1TO[] $transitions transitions
	 *
	 * @return $this
	 */
	public function setTransitions( $transitions ) {
		$this->container['transitions'] = $transitions;

		return $this;
	}
	/**
	 * Returns true if offset exists. False otherwise.
	 *
	 * @param integer $offset Offset
	 *
	 * @return boolean
	 */
	public function offsetExists( $offset ) {
		return isset( $this->container[ $offset ] );
	}

	/**
	 * Gets offset.
	 *
	 * @param integer $offset Offset
	 *
	 * @return mixed
	 */
	public function offsetGet( $offset ) {
		return isset( $this->container[ $offset ] ) ? $this->container[ $offset ] : null;
	}

	/**
	 * Sets value based on offset.
	 *
	 * @param integer $offset Offset
	 * @param mixed   $value  Value to be set
	 *
	 * @return void
	 */
	public function offsetSet( $offset, $value ) {
		if ( is_null( $offset ) ) {
			$this->container[] = $value;
		} else {
			$this->container[ $offset ] = $value;
		}
	}

	/**
	 * Unsets offset.
	 *
	 * @param integer $offset Offset
	 *
	 * @return void
	 */
	public function offsetUnset( $offset ) {
		unset( $this->container[ $offset ] );
	}

	/**
	 * Gets the string presentation of the object
	 *
	 * @return string
	 */
	public function __toString() {
		if ( defined( 'JSON_PRETTY_PRINT' ) ) { // use JSON pretty print
			return json_encode(
				ObjectSerializer::sanitizeForSerialization( $this ),
				JSON_PRETTY_PRINT
			);
		}

		return json_encode( ObjectSerializer::sanitizeForSerialization( $this ) );
	}
}


