<?php
/**
 * TargetMediaV1TO
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * getNEXT REST API
 *
 * Welcome to the getNEXT Platform REST API Reference! You can use this REST API to develop integrations between getNEXT and other applications or script interactions with getNEXT.
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * TargetMediaV1TO Class Doc Comment
 *
 * @category    Class
 * @description Describes one Target Media
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TargetMediaV1TO implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'TargetMediaV1TO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'height' => 'string',
        'id' => 'int',
        'intent' => 'int',
        'name' => 'string',
        'orientation' => 'int',
        'units' => 'string',
        'width' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'height' => null,
        'id' => 'int64',
        'intent' => 'int32',
        'name' => null,
        'orientation' => 'int32',
        'units' => null,
        'width' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'height' => 'height',
        'id' => 'id',
        'intent' => 'intent',
        'name' => 'name',
        'orientation' => 'orientation',
        'units' => 'units',
        'width' => 'width'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'height' => 'setHeight',
        'id' => 'setId',
        'intent' => 'setIntent',
        'name' => 'setName',
        'orientation' => 'setOrientation',
        'units' => 'setUnits',
        'width' => 'setWidth'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'height' => 'getHeight',
        'id' => 'getId',
        'intent' => 'getIntent',
        'name' => 'getName',
        'orientation' => 'getOrientation',
        'units' => 'getUnits',
        'width' => 'getWidth'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    const INTENT_1 = 1;
    const INTENT_2 = 2;
    const INTENT_3 = 3;
    const INTENT_4 = 4;
    const INTENT_5 = 5;
    const INTENT_6 = 6;
    const ORIENTATION_0 = 0;
    const ORIENTATION_1 = 1;
    const ORIENTATION_2 = 2;
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getIntentAllowableValues()
    {
        return [
            self::INTENT_1,
            self::INTENT_2,
            self::INTENT_3,
            self::INTENT_4,
            self::INTENT_5,
            self::INTENT_6,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getOrientationAllowableValues()
    {
        return [
            self::ORIENTATION_0,
            self::ORIENTATION_1,
            self::ORIENTATION_2,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['height'] = isset($data['height']) ? $data['height'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['intent'] = isset($data['intent']) ? $data['intent'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['orientation'] = isset($data['orientation']) ? $data['orientation'] : null;
        $this->container['units'] = isset($data['units']) ? $data['units'] : null;
        $this->container['width'] = isset($data['width']) ? $data['width'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['intent'] === null) {
            $invalid_properties[] = "'intent' can't be null";
        }
        $allowed_values = $this->getIntentAllowableValues();
        if (!in_array($this->container['intent'], $allowed_values)) {
            $invalid_properties[] = sprintf(
                "invalid value for 'intent', must be one of '%s'",
                implode("', '", $allowed_values)
            );
        }

        if ($this->container['orientation'] === null) {
            $invalid_properties[] = "'orientation' can't be null";
        }
        $allowed_values = $this->getOrientationAllowableValues();
        if (!in_array($this->container['orientation'], $allowed_values)) {
            $invalid_properties[] = sprintf(
                "invalid value for 'orientation', must be one of '%s'",
                implode("', '", $allowed_values)
            );
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['intent'] === null) {
            return false;
        }
        $allowed_values = $this->getIntentAllowableValues();
        if (!in_array($this->container['intent'], $allowed_values)) {
            return false;
        }
        if ($this->container['orientation'] === null) {
            return false;
        }
        $allowed_values = $this->getOrientationAllowableValues();
        if (!in_array($this->container['orientation'], $allowed_values)) {
            return false;
        }
        return true;
    }


    /**
     * Gets height
     * @return string
     */
    public function getHeight()
    {
        return $this->container['height'];
    }

    /**
     * Sets height
     * @param string $height the height of the target area in the units specified by units
     * @return $this
     */
    public function setHeight($height)
    {
        $this->container['height'] = $height;

        return $this;
    }

    /**
     * Gets id
     * @return int
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     * @param int $id the ID of the object which may be passed to various APIs to fetch or update the object
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets intent
     * @return int
     */
    public function getIntent()
    {
        return $this->container['intent'];
    }

    /**
     * Sets intent
     * @param int $intent a constant that identifies the intended consumption device of this Job's file
     * @return $this
     */
    public function setIntent($intent)
    {
        $allowed_values = $this->getIntentAllowableValues();
        if (!in_array($intent, $allowed_values)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'intent', must be one of '%s'",
                    implode("', '", $allowed_values)
                )
            );
        }
        $this->container['intent'] = $intent;

        return $this;
    }

    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     * @param string $name the name of the object, if it has one
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets orientation
     * @return int
     */
    public function getOrientation()
    {
        return $this->container['orientation'];
    }

    /**
     * Sets orientation
     * @param int $orientation the display orientation
     * @return $this
     */
    public function setOrientation($orientation)
    {
        $allowed_values = $this->getOrientationAllowableValues();
        if (!in_array($orientation, $allowed_values)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'orientation', must be one of '%s'",
                    implode("', '", $allowed_values)
                )
            );
        }
        $this->container['orientation'] = $orientation;

        return $this;
    }

    /**
     * Gets units
     * @return string
     */
    public function getUnits()
    {
        return $this->container['units'];
    }

    /**
     * Sets units
     * @param string $units the measurement unit used by width and height
     * @return $this
     */
    public function setUnits($units)
    {
        $this->container['units'] = $units;

        return $this;
    }

    /**
     * Gets width
     * @return string
     */
    public function getWidth()
    {
        return $this->container['width'];
    }

    /**
     * Sets width
     * @param string $width the width of the target area in the units specified by units
     * @return $this
     */
    public function setWidth($width)
    {
        $this->container['width'] = $width;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


