<?php
/**
 * FileApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TruEdit REST API
 *
 * Welcome to the TruEdit Platform REST API Reference! You can use this REST API to develop integrations between TruEdit and other applications or script interactions with TruEdit.
 *
 * OpenAPI spec version: 1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * FileApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FileApiTest extends \PHPUnit_Framework_TestCase {


	/**
	 * Setup before running any test cases
	 */
	public static function setUpBeforeClass() {
	}

	/**
	 * Setup before running each test case
	 */
	public function setUp() {
	}

	/**
	 * Clean up after running each test case
	 */
	public function tearDown() {
	}

	/**
	 * Clean up after running all test cases
	 */
	public static function tearDownAfterClass() {
	}

	/**
	 * Test case for retrieveFileUsingGET
	 *
	 * Fetch a specific file.
	 *
	 */
	public function testRetrieveFileUsingGET() {
	}

	/**
	 * Test case for retrieveJobOutputFileUsingGET
	 *
	 * Fetch a specific output file for a specific job.
	 *
	 */
	public function testRetrieveJobOutputFileUsingGET() {
	}

	/**
	 * Test case for retrieveJobWorkingFileUsingGET
	 *
	 * Fetch the working file for a specific job.
	 *
	 */
	public function testRetrieveJobWorkingFileUsingGET() {
	}
}
