<?php
/**
 * StatusApi
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * TruEdit REST API
 *
 * Welcome to the TruEdit Platform REST API Reference! You can use this REST API to develop integrations between TruEdit and other applications or script interactions with TruEdit.
 *
 * OpenAPI spec version: 1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.3.1
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Swagger\Client\ApiException;
use Swagger\Client\Configuration;
use Swagger\Client\HeaderSelector;
use Swagger\Client\ObjectSerializer;

/**
 * StatusApi Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class StatusApi {

	/**
	 * @var ClientInterface
	 */
	protected $client;

	/**
	 * @var Configuration
	 */
	protected $config;

	/**
	 * @param ClientInterface $client
	 * @param Configuration   $config
	 * @param HeaderSelector  $selector
	 */
	public function __construct(
		ClientInterface $client = null,
		Configuration $config = null,
		HeaderSelector $selector = null
	) {
		$this->client         = $client ?: new Client();
		$this->config         = $config ?: new Configuration();
		$this->headerSelector = $selector ?: new HeaderSelector();
	}

	/**
	 * @return Configuration
	 */
	public function getConfig() {
		return $this->config;
	}

	/**
	 * Operation createNewUsingPOST
	 *
	 * Create one or more Status
	 *
	 * @param  \Swagger\Client\Model\StatusV1ListTO $new_status newStatus (required)
	 * @param  string $x_api_key x_api_key (optional)
	 * @param  string $x_app_api_key x_app_api_key (optional)
	 * @param  string $accept_language accept_language (optional)
	 *
	 * @throws \Swagger\Client\ApiException on non-2xx response
	 * @throws \InvalidArgumentException
	 * @return \Swagger\Client\Model\API1ResultListResponseStatusV1TO_
	 */
	public function createNewUsingPOST( $new_status, $x_api_key = null, $x_app_api_key = null, $accept_language = null ) {
		list($response) = $this->createNewUsingPOSTWithHttpInfo( $new_status, $x_api_key, $x_app_api_key, $accept_language );
		return $response;
	}

	/**
	 * Operation createNewUsingPOSTWithHttpInfo
	 *
	 * Create one or more Status
	 *
	 * @param  \Swagger\Client\Model\StatusV1ListTO $new_status newStatus (required)
	 * @param  string $x_api_key (optional)
	 * @param  string $x_app_api_key (optional)
	 * @param  string $accept_language (optional)
	 *
	 * @throws \Swagger\Client\ApiException on non-2xx response
	 * @throws \InvalidArgumentException
	 * @return array of \Swagger\Client\Model\API1ResultListResponseStatusV1TO_, HTTP status code, HTTP response headers (array of strings)
	 */
	public function createNewUsingPOSTWithHttpInfo( $new_status, $x_api_key = null, $x_app_api_key = null, $accept_language = null ) {
		$returnType = '\Swagger\Client\Model\API1ResultListResponseStatusV1TO_';
		$request    = $this->createNewUsingPOSTRequest( $new_status, $x_api_key, $x_app_api_key, $accept_language );

		try {
			$options = $this->createHttpClientOption();
			try {
				$response = $this->client->send( $request, $options );
			} catch ( RequestException $e ) {
				throw new ApiException(
					"[{$e->getCode()}] {$e->getMessage()}",
					$e->getCode(),
					$e->getResponse() ? $e->getResponse()->getHeaders() : null,
					$e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
				);
			}

			$statusCode = $response->getStatusCode();

			if ( $statusCode < 200 || $statusCode > 299 ) {
				throw new ApiException(
					sprintf(
						'[%d] Error connecting to the API (%s)',
						$statusCode,
						$request->getUri()
					),
					$statusCode,
					$response->getHeaders(),
					$response->getBody()
				);
			}

			$responseBody = $response->getBody();
			if ( $returnType === '\SplFileObject' ) {
				$content = $responseBody; //stream goes to serializer
			} else {
				$content = $responseBody->getContents();
				if ( $returnType !== 'string' ) {
					$content = json_decode( $content );
				}
			}

			return [
				ObjectSerializer::deserialize( $content, $returnType, [] ),
				$response->getStatusCode(),
				$response->getHeaders(),
			];

		} catch ( ApiException $e ) {
			switch ( $e->getCode() ) {
				case 200:
					$data = ObjectSerializer::deserialize(
						$e->getResponseBody(),
						'\Swagger\Client\Model\API1ResultListResponseStatusV1TO_',
						$e->getResponseHeaders()
					);
					$e->setResponseObject( $data );
					break;
			}
			throw $e;
		}
	}

	/**
	 * Operation createNewUsingPOSTAsync
	 *
	 * Create one or more Status
	 *
	 * @param  \Swagger\Client\Model\StatusV1ListTO $new_status newStatus (required)
	 * @param  string $x_api_key (optional)
	 * @param  string $x_app_api_key (optional)
	 * @param  string $accept_language (optional)
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function createNewUsingPOSTAsync( $new_status, $x_api_key = null, $x_app_api_key = null, $accept_language = null ) {
		return $this->createNewUsingPOSTAsyncWithHttpInfo( $new_status, $x_api_key, $x_app_api_key, $accept_language )
			->then(
				function ( $response ) {
					return $response[0];
				}
			);
	}

	/**
	 * Operation createNewUsingPOSTAsyncWithHttpInfo
	 *
	 * Create one or more Status
	 *
	 * @param  \Swagger\Client\Model\StatusV1ListTO $new_status newStatus (required)
	 * @param  string $x_api_key (optional)
	 * @param  string $x_app_api_key (optional)
	 * @param  string $accept_language (optional)
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function createNewUsingPOSTAsyncWithHttpInfo( $new_status, $x_api_key = null, $x_app_api_key = null, $accept_language = null ) {
		$returnType = '\Swagger\Client\Model\API1ResultListResponseStatusV1TO_';
		$request    = $this->createNewUsingPOSTRequest( $new_status, $x_api_key, $x_app_api_key, $accept_language );

		return $this->client
			->sendAsync( $request, $this->createHttpClientOption() )
			->then(
				function ( $response ) use ( $returnType ) {
					$responseBody = $response->getBody();
					if ( $returnType === '\SplFileObject' ) {
						$content = $responseBody; //stream goes to serializer
					} else {
						$content = $responseBody->getContents();
						if ( $returnType !== 'string' ) {
							$content = json_decode( $content );
						}
					}

					return [
						ObjectSerializer::deserialize( $content, $returnType, [] ),
						$response->getStatusCode(),
						$response->getHeaders(),
					];
				},
				function ( $exception ) {
					$response   = $exception->getResponse();
					$statusCode = $response->getStatusCode();
					throw new ApiException(
						sprintf(
							'[%d] Error connecting to the API (%s)',
							$statusCode,
							$exception->getRequest()->getUri()
						),
						$statusCode,
						$response->getHeaders(),
						$response->getBody()
					);
				}
			);
	}

	/**
	 * Create request for operation 'createNewUsingPOST'
	 *
	 * @param  \Swagger\Client\Model\StatusV1ListTO $new_status newStatus (required)
	 * @param  string $x_api_key (optional)
	 * @param  string $x_app_api_key (optional)
	 * @param  string $accept_language (optional)
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Psr7\Request
	 */
	protected function createNewUsingPOSTRequest( $new_status, $x_api_key = null, $x_app_api_key = null, $accept_language = null ) {
		// verify the required parameter 'new_status' is set
		if ( $new_status === null ) {
			throw new \InvalidArgumentException(
				'Missing the required parameter $new_status when calling createNewUsingPOST'
			);
		}

		$resourcePath = '/1/status';
		$formParams   = [];
		$queryParams  = [];
		$headerParams = [];
		$httpBody     = '';
		$multipart    = false;

		// header params
		if ( $x_api_key !== null ) {
			$headerParams['x-api-key'] = ObjectSerializer::toHeaderValue( $x_api_key );
		}
		// header params
		if ( $x_app_api_key !== null ) {
			$headerParams['x-app-api-key'] = ObjectSerializer::toHeaderValue( $x_app_api_key );
		}
		// header params
		if ( $accept_language !== null ) {
			$headerParams['Accept-Language'] = ObjectSerializer::toHeaderValue( $accept_language );
		}

		// body params
		$_tempBody = null;
		if ( isset( $new_status ) ) {
			$_tempBody = $new_status;
		}

		if ( $multipart ) {
			$headers = $this->headerSelector->selectHeadersForMultipart(
				[ '*/*' ]
			);
		} else {
			$headers = $this->headerSelector->selectHeaders(
				[ '*/*' ],
				[ 'application/json' ]
			);
		}

		// for model (json/xml)
		if ( isset( $_tempBody ) ) {
			// $_tempBody is the method argument, if present
			$httpBody = $_tempBody;
			// \stdClass has no __toString(), so we should encode it manually
			if ( $httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json' ) {
				$httpBody = \GuzzleHttp\json_encode( $httpBody );
			}
		} elseif ( count( $formParams ) > 0 ) {
			if ( $multipart ) {
				$multipartContents = [];
				foreach ( $formParams as $formParamName => $formParamValue ) {
					$multipartContents[] = [
						'name'     => $formParamName,
						'contents' => $formParamValue,
					];
				}
				// for HTTP post (form)
				$httpBody = new MultipartStream( $multipartContents );

			} elseif ( $headers['Content-Type'] === 'application/json' ) {
				$httpBody = \GuzzleHttp\json_encode( $formParams );

			} else {
				// for HTTP post (form)
				$httpBody = \GuzzleHttp\Psr7\build_query( $formParams );
			}
		}

		$defaultHeaders = [];
		if ( $this->config->getUserAgent() ) {
			$defaultHeaders['User-Agent'] = $this->config->getUserAgent();
		}

		$headers = array_merge(
			$defaultHeaders,
			$headerParams,
			$headers
		);

		$query = \GuzzleHttp\Psr7\build_query( $queryParams );
		return new Request(
			'POST',
			$this->config->getHost() . $resourcePath . ( $query ? "?{$query}" : '' ),
			$headers,
			$httpBody
		);
	}

	/**
	 * Operation deleteOneUsingDELETE
	 *
	 * Delete a single Status object.
	 *
	 * @param  int $id id (required)
	 * @param  string $x_api_key x_api_key (optional)
	 * @param  string $x_app_api_key x_app_api_key (optional)
	 * @param  string $accept_language accept_language (optional)
	 *
	 * @throws \Swagger\Client\ApiException on non-2xx response
	 * @throws \InvalidArgumentException
	 * @return \Swagger\Client\Model\API1ResponseMessage
	 */
	public function deleteOneUsingDELETE( $id, $x_api_key = null, $x_app_api_key = null, $accept_language = null ) {
		list($response) = $this->deleteOneUsingDELETEWithHttpInfo( $id, $x_api_key, $x_app_api_key, $accept_language );
		return $response;
	}

	/**
	 * Operation deleteOneUsingDELETEWithHttpInfo
	 *
	 * Delete a single Status object.
	 *
	 * @param  int $id id (required)
	 * @param  string $x_api_key (optional)
	 * @param  string $x_app_api_key (optional)
	 * @param  string $accept_language (optional)
	 *
	 * @throws \Swagger\Client\ApiException on non-2xx response
	 * @throws \InvalidArgumentException
	 * @return array of \Swagger\Client\Model\API1ResponseMessage, HTTP status code, HTTP response headers (array of strings)
	 */
	public function deleteOneUsingDELETEWithHttpInfo( $id, $x_api_key = null, $x_app_api_key = null, $accept_language = null ) {
		$returnType = '\Swagger\Client\Model\API1ResponseMessage';
		$request    = $this->deleteOneUsingDELETERequest( $id, $x_api_key, $x_app_api_key, $accept_language );

		try {
			$options = $this->createHttpClientOption();
			try {
				$response = $this->client->send( $request, $options );
			} catch ( RequestException $e ) {
				throw new ApiException(
					"[{$e->getCode()}] {$e->getMessage()}",
					$e->getCode(),
					$e->getResponse() ? $e->getResponse()->getHeaders() : null,
					$e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
				);
			}

			$statusCode = $response->getStatusCode();

			if ( $statusCode < 200 || $statusCode > 299 ) {
				throw new ApiException(
					sprintf(
						'[%d] Error connecting to the API (%s)',
						$statusCode,
						$request->getUri()
					),
					$statusCode,
					$response->getHeaders(),
					$response->getBody()
				);
			}

			$responseBody = $response->getBody();
			if ( $returnType === '\SplFileObject' ) {
				$content = $responseBody; //stream goes to serializer
			} else {
				$content = $responseBody->getContents();
				if ( $returnType !== 'string' ) {
					$content = json_decode( $content );
				}
			}

			return [
				ObjectSerializer::deserialize( $content, $returnType, [] ),
				$response->getStatusCode(),
				$response->getHeaders(),
			];

		} catch ( ApiException $e ) {
			switch ( $e->getCode() ) {
				case 200:
					$data = ObjectSerializer::deserialize(
						$e->getResponseBody(),
						'\Swagger\Client\Model\API1ResponseMessage',
						$e->getResponseHeaders()
					);
					$e->setResponseObject( $data );
					break;
			}
			throw $e;
		}
	}

	/**
	 * Operation deleteOneUsingDELETEAsync
	 *
	 * Delete a single Status object.
	 *
	 * @param  int $id id (required)
	 * @param  string $x_api_key (optional)
	 * @param  string $x_app_api_key (optional)
	 * @param  string $accept_language (optional)
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function deleteOneUsingDELETEAsync( $id, $x_api_key = null, $x_app_api_key = null, $accept_language = null ) {
		return $this->deleteOneUsingDELETEAsyncWithHttpInfo( $id, $x_api_key, $x_app_api_key, $accept_language )
			->then(
				function ( $response ) {
					return $response[0];
				}
			);
	}

	/**
	 * Operation deleteOneUsingDELETEAsyncWithHttpInfo
	 *
	 * Delete a single Status object.
	 *
	 * @param  int $id id (required)
	 * @param  string $x_api_key (optional)
	 * @param  string $x_app_api_key (optional)
	 * @param  string $accept_language (optional)
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function deleteOneUsingDELETEAsyncWithHttpInfo( $id, $x_api_key = null, $x_app_api_key = null, $accept_language = null ) {
		$returnType = '\Swagger\Client\Model\API1ResponseMessage';
		$request    = $this->deleteOneUsingDELETERequest( $id, $x_api_key, $x_app_api_key, $accept_language );

		return $this->client
			->sendAsync( $request, $this->createHttpClientOption() )
			->then(
				function ( $response ) use ( $returnType ) {
					$responseBody = $response->getBody();
					if ( $returnType === '\SplFileObject' ) {
						$content = $responseBody; //stream goes to serializer
					} else {
						$content = $responseBody->getContents();
						if ( $returnType !== 'string' ) {
							$content = json_decode( $content );
						}
					}

					return [
						ObjectSerializer::deserialize( $content, $returnType, [] ),
						$response->getStatusCode(),
						$response->getHeaders(),
					];
				},
				function ( $exception ) {
					$response   = $exception->getResponse();
					$statusCode = $response->getStatusCode();
					throw new ApiException(
						sprintf(
							'[%d] Error connecting to the API (%s)',
							$statusCode,
							$exception->getRequest()->getUri()
						),
						$statusCode,
						$response->getHeaders(),
						$response->getBody()
					);
				}
			);
	}

	/**
	 * Create request for operation 'deleteOneUsingDELETE'
	 *
	 * @param  int $id id (required)
	 * @param  string $x_api_key (optional)
	 * @param  string $x_app_api_key (optional)
	 * @param  string $accept_language (optional)
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Psr7\Request
	 */
	protected function deleteOneUsingDELETERequest( $id, $x_api_key = null, $x_app_api_key = null, $accept_language = null ) {
		// verify the required parameter 'id' is set
		if ( $id === null ) {
			throw new \InvalidArgumentException(
				'Missing the required parameter $id when calling deleteOneUsingDELETE'
			);
		}

		$resourcePath = '/1/status/{id}';
		$formParams   = [];
		$queryParams  = [];
		$headerParams = [];
		$httpBody     = '';
		$multipart    = false;

		// header params
		if ( $x_api_key !== null ) {
			$headerParams['x-api-key'] = ObjectSerializer::toHeaderValue( $x_api_key );
		}
		// header params
		if ( $x_app_api_key !== null ) {
			$headerParams['x-app-api-key'] = ObjectSerializer::toHeaderValue( $x_app_api_key );
		}
		// header params
		if ( $accept_language !== null ) {
			$headerParams['Accept-Language'] = ObjectSerializer::toHeaderValue( $accept_language );
		}

		// path params
		if ( $id !== null ) {
			$resourcePath = str_replace(
				'{' . 'id' . '}',
				ObjectSerializer::toPathValue( $id ),
				$resourcePath
			);
		}

		// body params
		$_tempBody = null;

		if ( $multipart ) {
			$headers = $this->headerSelector->selectHeadersForMultipart(
				[ '*/*' ]
			);
		} else {
			$headers = $this->headerSelector->selectHeaders(
				[ '*/*' ],
				[]
			);
		}

		// for model (json/xml)
		if ( isset( $_tempBody ) ) {
			// $_tempBody is the method argument, if present
			$httpBody = $_tempBody;
			// \stdClass has no __toString(), so we should encode it manually
			if ( $httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json' ) {
				$httpBody = \GuzzleHttp\json_encode( $httpBody );
			}
		} elseif ( count( $formParams ) > 0 ) {
			if ( $multipart ) {
				$multipartContents = [];
				foreach ( $formParams as $formParamName => $formParamValue ) {
					$multipartContents[] = [
						'name'     => $formParamName,
						'contents' => $formParamValue,
					];
				}
				// for HTTP post (form)
				$httpBody = new MultipartStream( $multipartContents );

			} elseif ( $headers['Content-Type'] === 'application/json' ) {
				$httpBody = \GuzzleHttp\json_encode( $formParams );

			} else {
				// for HTTP post (form)
				$httpBody = \GuzzleHttp\Psr7\build_query( $formParams );
			}
		}

		$defaultHeaders = [];
		if ( $this->config->getUserAgent() ) {
			$defaultHeaders['User-Agent'] = $this->config->getUserAgent();
		}

		$headers = array_merge(
			$defaultHeaders,
			$headerParams,
			$headers
		);

		$query = \GuzzleHttp\Psr7\build_query( $queryParams );
		return new Request(
			'DELETE',
			$this->config->getHost() . $resourcePath . ( $query ? "?{$query}" : '' ),
			$headers,
			$httpBody
		);
	}

	/**
	 * Operation fetchAllUsingGET5
	 *
	 * Fetch all available Status objects.
	 *
	 * @param  bool $minimal minimal (optional, default to false)
	 * @param  int $page_number pageNumber (optional, default to 1)
	 * @param  int $page_size pageSize (optional, default to 100)
	 * @param  string[] $order_by orderBy (optional, default to name asc)
	 * @param  string $x_api_key x_api_key (optional)
	 * @param  string $x_app_api_key x_app_api_key (optional)
	 * @param  string $accept_language accept_language (optional)
	 * @param  \DateTime $if_modified_since if_modified_since (optional)
	 *
	 * @throws \Swagger\Client\ApiException on non-2xx response
	 * @throws \InvalidArgumentException
	 * @return \Swagger\Client\Model\API1ResultListResponseStatusV1TO_
	 */
	public function fetchAllUsingGET5( $minimal = 'false', $page_number = '1', $page_size = '100', $order_by = 'name asc', $x_api_key = null, $x_app_api_key = null, $accept_language = null, $if_modified_since = null ) {
		list($response) = $this->fetchAllUsingGET5WithHttpInfo( $minimal, $page_number, $page_size, $order_by, $x_api_key, $x_app_api_key, $accept_language, $if_modified_since );
		return $response;
	}

	/**
	 * Operation fetchAllUsingGET5WithHttpInfo
	 *
	 * Fetch all available Status objects.
	 *
	 * @param  bool $minimal minimal (optional, default to false)
	 * @param  int $page_number pageNumber (optional, default to 1)
	 * @param  int $page_size pageSize (optional, default to 100)
	 * @param  string[] $order_by orderBy (optional, default to name asc)
	 * @param  string $x_api_key (optional)
	 * @param  string $x_app_api_key (optional)
	 * @param  string $accept_language (optional)
	 * @param  \DateTime $if_modified_since (optional)
	 *
	 * @throws \Swagger\Client\ApiException on non-2xx response
	 * @throws \InvalidArgumentException
	 * @return array of \Swagger\Client\Model\API1ResultListResponseStatusV1TO_, HTTP status code, HTTP response headers (array of strings)
	 */
	public function fetchAllUsingGET5WithHttpInfo( $minimal = 'false', $page_number = '1', $page_size = '100', $order_by = 'name asc', $x_api_key = null, $x_app_api_key = null, $accept_language = null, $if_modified_since = null ) {
		$returnType = '\Swagger\Client\Model\API1ResultListResponseStatusV1TO_';
		$request    = $this->fetchAllUsingGET5Request( $minimal, $page_number, $page_size, $order_by, $x_api_key, $x_app_api_key, $accept_language, $if_modified_since );

		try {
			$options = $this->createHttpClientOption();
			try {
				$response = $this->client->send( $request, $options );
			} catch ( RequestException $e ) {
				throw new ApiException(
					"[{$e->getCode()}] {$e->getMessage()}",
					$e->getCode(),
					$e->getResponse() ? $e->getResponse()->getHeaders() : null,
					$e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
				);
			}

			$statusCode = $response->getStatusCode();

			if ( $statusCode < 200 || $statusCode > 299 ) {
				throw new ApiException(
					sprintf(
						'[%d] Error connecting to the API (%s)',
						$statusCode,
						$request->getUri()
					),
					$statusCode,
					$response->getHeaders(),
					$response->getBody()
				);
			}

			$responseBody = $response->getBody();
			if ( $returnType === '\SplFileObject' ) {
				$content = $responseBody; //stream goes to serializer
			} else {
				$content = $responseBody->getContents();
				if ( $returnType !== 'string' ) {
					$content = json_decode( $content );
				}
			}

			return [
				ObjectSerializer::deserialize( $content, $returnType, [] ),
				$response->getStatusCode(),
				$response->getHeaders(),
			];

		} catch ( ApiException $e ) {
			switch ( $e->getCode() ) {
				case 200:
					$data = ObjectSerializer::deserialize(
						$e->getResponseBody(),
						'\Swagger\Client\Model\API1ResultListResponseStatusV1TO_',
						$e->getResponseHeaders()
					);
					$e->setResponseObject( $data );
					break;
			}
			throw $e;
		}
	}

	/**
	 * Operation fetchAllUsingGET5Async
	 *
	 * Fetch all available Status objects.
	 *
	 * @param  bool $minimal minimal (optional, default to false)
	 * @param  int $page_number pageNumber (optional, default to 1)
	 * @param  int $page_size pageSize (optional, default to 100)
	 * @param  string[] $order_by orderBy (optional, default to name asc)
	 * @param  string $x_api_key (optional)
	 * @param  string $x_app_api_key (optional)
	 * @param  string $accept_language (optional)
	 * @param  \DateTime $if_modified_since (optional)
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function fetchAllUsingGET5Async( $minimal = 'false', $page_number = '1', $page_size = '100', $order_by = 'name asc', $x_api_key = null, $x_app_api_key = null, $accept_language = null, $if_modified_since = null ) {
		return $this->fetchAllUsingGET5AsyncWithHttpInfo( $minimal, $page_number, $page_size, $order_by, $x_api_key, $x_app_api_key, $accept_language, $if_modified_since )
			->then(
				function ( $response ) {
					return $response[0];
				}
			);
	}

	/**
	 * Operation fetchAllUsingGET5AsyncWithHttpInfo
	 *
	 * Fetch all available Status objects.
	 *
	 * @param  bool $minimal minimal (optional, default to false)
	 * @param  int $page_number pageNumber (optional, default to 1)
	 * @param  int $page_size pageSize (optional, default to 100)
	 * @param  string[] $order_by orderBy (optional, default to name asc)
	 * @param  string $x_api_key (optional)
	 * @param  string $x_app_api_key (optional)
	 * @param  string $accept_language (optional)
	 * @param  \DateTime $if_modified_since (optional)
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function fetchAllUsingGET5AsyncWithHttpInfo( $minimal = 'false', $page_number = '1', $page_size = '100', $order_by = 'name asc', $x_api_key = null, $x_app_api_key = null, $accept_language = null, $if_modified_since = null ) {
		$returnType = '\Swagger\Client\Model\API1ResultListResponseStatusV1TO_';
		$request    = $this->fetchAllUsingGET5Request( $minimal, $page_number, $page_size, $order_by, $x_api_key, $x_app_api_key, $accept_language, $if_modified_since );

		return $this->client
			->sendAsync( $request, $this->createHttpClientOption() )
			->then(
				function ( $response ) use ( $returnType ) {
					$responseBody = $response->getBody();
					if ( $returnType === '\SplFileObject' ) {
						$content = $responseBody; //stream goes to serializer
					} else {
						$content = $responseBody->getContents();
						if ( $returnType !== 'string' ) {
							$content = json_decode( $content );
						}
					}

					return [
						ObjectSerializer::deserialize( $content, $returnType, [] ),
						$response->getStatusCode(),
						$response->getHeaders(),
					];
				},
				function ( $exception ) {
					$response   = $exception->getResponse();
					$statusCode = $response->getStatusCode();
					throw new ApiException(
						sprintf(
							'[%d] Error connecting to the API (%s)',
							$statusCode,
							$exception->getRequest()->getUri()
						),
						$statusCode,
						$response->getHeaders(),
						$response->getBody()
					);
				}
			);
	}

	/**
	 * Create request for operation 'fetchAllUsingGET5'
	 *
	 * @param  bool $minimal minimal (optional, default to false)
	 * @param  int $page_number pageNumber (optional, default to 1)
	 * @param  int $page_size pageSize (optional, default to 100)
	 * @param  string[] $order_by orderBy (optional, default to name asc)
	 * @param  string $x_api_key (optional)
	 * @param  string $x_app_api_key (optional)
	 * @param  string $accept_language (optional)
	 * @param  \DateTime $if_modified_since (optional)
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Psr7\Request
	 */
	protected function fetchAllUsingGET5Request( $minimal = 'false', $page_number = '1', $page_size = '100', $order_by = 'name asc', $x_api_key = null, $x_app_api_key = null, $accept_language = null, $if_modified_since = null ) {

		$resourcePath = '/1/status';
		$formParams   = [];
		$queryParams  = [];
		$headerParams = [];
		$httpBody     = '';
		$multipart    = false;

		// query params
		if ( $minimal !== null ) {
			$queryParams['minimal'] = ObjectSerializer::toQueryValue( $minimal );
		}
		// query params
		if ( $page_number !== null ) {
			$queryParams['pageNumber'] = ObjectSerializer::toQueryValue( $page_number );
		}
		// query params
		if ( $page_size !== null ) {
			$queryParams['pageSize'] = ObjectSerializer::toQueryValue( $page_size );
		}
		// query params
		if ( is_array( $order_by ) ) {
			$order_by = ObjectSerializer::serializeCollection( $order_by, 'multi', true );
		}
		if ( $order_by !== null ) {
			$queryParams['orderBy'] = ObjectSerializer::toQueryValue( $order_by );
		}
		// header params
		if ( $x_api_key !== null ) {
			$headerParams['x-api-key'] = ObjectSerializer::toHeaderValue( $x_api_key );
		}
		// header params
		if ( $x_app_api_key !== null ) {
			$headerParams['x-app-api-key'] = ObjectSerializer::toHeaderValue( $x_app_api_key );
		}
		// header params
		if ( $accept_language !== null ) {
			$headerParams['Accept-Language'] = ObjectSerializer::toHeaderValue( $accept_language );
		}
		// header params
		if ( $if_modified_since !== null ) {
			$headerParams['If-Modified-Since'] = ObjectSerializer::toHeaderValue( $if_modified_since );
		}

		// body params
		$_tempBody = null;

		if ( $multipart ) {
			$headers = $this->headerSelector->selectHeadersForMultipart(
				[ '*/*' ]
			);
		} else {
			$headers = $this->headerSelector->selectHeaders(
				[ '*/*' ],
				[]
			);
		}

		// for model (json/xml)
		if ( isset( $_tempBody ) ) {
			// $_tempBody is the method argument, if present
			$httpBody = $_tempBody;
			// \stdClass has no __toString(), so we should encode it manually
			if ( $httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json' ) {
				$httpBody = \GuzzleHttp\json_encode( $httpBody );
			}
		} elseif ( count( $formParams ) > 0 ) {
			if ( $multipart ) {
				$multipartContents = [];
				foreach ( $formParams as $formParamName => $formParamValue ) {
					$multipartContents[] = [
						'name'     => $formParamName,
						'contents' => $formParamValue,
					];
				}
				// for HTTP post (form)
				$httpBody = new MultipartStream( $multipartContents );

			} elseif ( $headers['Content-Type'] === 'application/json' ) {
				$httpBody = \GuzzleHttp\json_encode( $formParams );

			} else {
				// for HTTP post (form)
				$httpBody = \GuzzleHttp\Psr7\build_query( $formParams );
			}
		}

		$defaultHeaders = [];
		if ( $this->config->getUserAgent() ) {
			$defaultHeaders['User-Agent'] = $this->config->getUserAgent();
		}

		$headers = array_merge(
			$defaultHeaders,
			$headerParams,
			$headers
		);

		$query = \GuzzleHttp\Psr7\build_query( $queryParams );
		return new Request(
			'GET',
			$this->config->getHost() . $resourcePath . ( $query ? "?{$query}" : '' ),
			$headers,
			$httpBody
		);
	}

	/**
	 * Operation fetchOneUsingGET1
	 *
	 * Fetch a single Status object.
	 *
	 * @param  int $id id (required)
	 * @param  string $x_api_key x_api_key (optional)
	 * @param  string $x_app_api_key x_app_api_key (optional)
	 * @param  string $accept_language accept_language (optional)
	 *
	 * @throws \Swagger\Client\ApiException on non-2xx response
	 * @throws \InvalidArgumentException
	 * @return \Swagger\Client\Model\API1SingleResultResponseStatusV1TO_
	 */
	public function fetchOneUsingGET1( $id, $x_api_key = null, $x_app_api_key = null, $accept_language = null ) {
		list($response) = $this->fetchOneUsingGET1WithHttpInfo( $id, $x_api_key, $x_app_api_key, $accept_language );
		return $response;
	}

	/**
	 * Operation fetchOneUsingGET1WithHttpInfo
	 *
	 * Fetch a single Status object.
	 *
	 * @param  int $id id (required)
	 * @param  string $x_api_key (optional)
	 * @param  string $x_app_api_key (optional)
	 * @param  string $accept_language (optional)
	 *
	 * @throws \Swagger\Client\ApiException on non-2xx response
	 * @throws \InvalidArgumentException
	 * @return array of \Swagger\Client\Model\API1SingleResultResponseStatusV1TO_, HTTP status code, HTTP response headers (array of strings)
	 */
	public function fetchOneUsingGET1WithHttpInfo( $id, $x_api_key = null, $x_app_api_key = null, $accept_language = null ) {
		$returnType = '\Swagger\Client\Model\API1SingleResultResponseStatusV1TO_';
		$request    = $this->fetchOneUsingGET1Request( $id, $x_api_key, $x_app_api_key, $accept_language );

		try {
			$options = $this->createHttpClientOption();
			try {
				$response = $this->client->send( $request, $options );
			} catch ( RequestException $e ) {
				throw new ApiException(
					"[{$e->getCode()}] {$e->getMessage()}",
					$e->getCode(),
					$e->getResponse() ? $e->getResponse()->getHeaders() : null,
					$e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
				);
			}

			$statusCode = $response->getStatusCode();

			if ( $statusCode < 200 || $statusCode > 299 ) {
				throw new ApiException(
					sprintf(
						'[%d] Error connecting to the API (%s)',
						$statusCode,
						$request->getUri()
					),
					$statusCode,
					$response->getHeaders(),
					$response->getBody()
				);
			}

			$responseBody = $response->getBody();
			if ( $returnType === '\SplFileObject' ) {
				$content = $responseBody; //stream goes to serializer
			} else {
				$content = $responseBody->getContents();
				if ( $returnType !== 'string' ) {
					$content = json_decode( $content );
				}
			}

			return [
				ObjectSerializer::deserialize( $content, $returnType, [] ),
				$response->getStatusCode(),
				$response->getHeaders(),
			];

		} catch ( ApiException $e ) {
			switch ( $e->getCode() ) {
				case 200:
					$data = ObjectSerializer::deserialize(
						$e->getResponseBody(),
						'\Swagger\Client\Model\API1SingleResultResponseStatusV1TO_',
						$e->getResponseHeaders()
					);
					$e->setResponseObject( $data );
					break;
			}
			throw $e;
		}
	}

	/**
	 * Operation fetchOneUsingGET1Async
	 *
	 * Fetch a single Status object.
	 *
	 * @param  int $id id (required)
	 * @param  string $x_api_key (optional)
	 * @param  string $x_app_api_key (optional)
	 * @param  string $accept_language (optional)
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function fetchOneUsingGET1Async( $id, $x_api_key = null, $x_app_api_key = null, $accept_language = null ) {
		return $this->fetchOneUsingGET1AsyncWithHttpInfo( $id, $x_api_key, $x_app_api_key, $accept_language )
			->then(
				function ( $response ) {
					return $response[0];
				}
			);
	}

	/**
	 * Operation fetchOneUsingGET1AsyncWithHttpInfo
	 *
	 * Fetch a single Status object.
	 *
	 * @param  int $id id (required)
	 * @param  string $x_api_key (optional)
	 * @param  string $x_app_api_key (optional)
	 * @param  string $accept_language (optional)
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function fetchOneUsingGET1AsyncWithHttpInfo( $id, $x_api_key = null, $x_app_api_key = null, $accept_language = null ) {
		$returnType = '\Swagger\Client\Model\API1SingleResultResponseStatusV1TO_';
		$request    = $this->fetchOneUsingGET1Request( $id, $x_api_key, $x_app_api_key, $accept_language );

		return $this->client
			->sendAsync( $request, $this->createHttpClientOption() )
			->then(
				function ( $response ) use ( $returnType ) {
					$responseBody = $response->getBody();
					if ( $returnType === '\SplFileObject' ) {
						$content = $responseBody; //stream goes to serializer
					} else {
						$content = $responseBody->getContents();
						if ( $returnType !== 'string' ) {
							$content = json_decode( $content );
						}
					}

					return [
						ObjectSerializer::deserialize( $content, $returnType, [] ),
						$response->getStatusCode(),
						$response->getHeaders(),
					];
				},
				function ( $exception ) {
					$response   = $exception->getResponse();
					$statusCode = $response->getStatusCode();
					throw new ApiException(
						sprintf(
							'[%d] Error connecting to the API (%s)',
							$statusCode,
							$exception->getRequest()->getUri()
						),
						$statusCode,
						$response->getHeaders(),
						$response->getBody()
					);
				}
			);
	}

	/**
	 * Create request for operation 'fetchOneUsingGET1'
	 *
	 * @param  int $id id (required)
	 * @param  string $x_api_key (optional)
	 * @param  string $x_app_api_key (optional)
	 * @param  string $accept_language (optional)
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Psr7\Request
	 */
	protected function fetchOneUsingGET1Request( $id, $x_api_key = null, $x_app_api_key = null, $accept_language = null ) {
		// verify the required parameter 'id' is set
		if ( $id === null ) {
			throw new \InvalidArgumentException(
				'Missing the required parameter $id when calling fetchOneUsingGET1'
			);
		}

		$resourcePath = '/1/status/{id}';
		$formParams   = [];
		$queryParams  = [];
		$headerParams = [];
		$httpBody     = '';
		$multipart    = false;

		// header params
		if ( $x_api_key !== null ) {
			$headerParams['x-api-key'] = ObjectSerializer::toHeaderValue( $x_api_key );
		}
		// header params
		if ( $x_app_api_key !== null ) {
			$headerParams['x-app-api-key'] = ObjectSerializer::toHeaderValue( $x_app_api_key );
		}
		// header params
		if ( $accept_language !== null ) {
			$headerParams['Accept-Language'] = ObjectSerializer::toHeaderValue( $accept_language );
		}

		// path params
		if ( $id !== null ) {
			$resourcePath = str_replace(
				'{' . 'id' . '}',
				ObjectSerializer::toPathValue( $id ),
				$resourcePath
			);
		}

		// body params
		$_tempBody = null;

		if ( $multipart ) {
			$headers = $this->headerSelector->selectHeadersForMultipart(
				[ '*/*' ]
			);
		} else {
			$headers = $this->headerSelector->selectHeaders(
				[ '*/*' ],
				[]
			);
		}

		// for model (json/xml)
		if ( isset( $_tempBody ) ) {
			// $_tempBody is the method argument, if present
			$httpBody = $_tempBody;
			// \stdClass has no __toString(), so we should encode it manually
			if ( $httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json' ) {
				$httpBody = \GuzzleHttp\json_encode( $httpBody );
			}
		} elseif ( count( $formParams ) > 0 ) {
			if ( $multipart ) {
				$multipartContents = [];
				foreach ( $formParams as $formParamName => $formParamValue ) {
					$multipartContents[] = [
						'name'     => $formParamName,
						'contents' => $formParamValue,
					];
				}
				// for HTTP post (form)
				$httpBody = new MultipartStream( $multipartContents );

			} elseif ( $headers['Content-Type'] === 'application/json' ) {
				$httpBody = \GuzzleHttp\json_encode( $formParams );

			} else {
				// for HTTP post (form)
				$httpBody = \GuzzleHttp\Psr7\build_query( $formParams );
			}
		}

		$defaultHeaders = [];
		if ( $this->config->getUserAgent() ) {
			$defaultHeaders['User-Agent'] = $this->config->getUserAgent();
		}

		$headers = array_merge(
			$defaultHeaders,
			$headerParams,
			$headers
		);

		$query = \GuzzleHttp\Psr7\build_query( $queryParams );
		return new Request(
			'GET',
			$this->config->getHost() . $resourcePath . ( $query ? "?{$query}" : '' ),
			$headers,
			$httpBody
		);
	}

	/**
	 * Operation updateOneUsingPUT
	 *
	 * Update one Status
	 *
	 * @param  int $id id (required)
	 * @param  \Swagger\Client\Model\StatusV1TO $updated_status updatedStatus (required)
	 * @param  string $x_api_key x_api_key (optional)
	 * @param  string $x_app_api_key x_app_api_key (optional)
	 * @param  string $accept_language accept_language (optional)
	 *
	 * @throws \Swagger\Client\ApiException on non-2xx response
	 * @throws \InvalidArgumentException
	 * @return \Swagger\Client\Model\API1SingleResultResponseStatusV1TO_
	 */
	public function updateOneUsingPUT( $id, $updated_status, $x_api_key = null, $x_app_api_key = null, $accept_language = null ) {
		list($response) = $this->updateOneUsingPUTWithHttpInfo( $id, $updated_status, $x_api_key, $x_app_api_key, $accept_language );
		return $response;
	}

	/**
	 * Operation updateOneUsingPUTWithHttpInfo
	 *
	 * Update one Status
	 *
	 * @param  int $id id (required)
	 * @param  \Swagger\Client\Model\StatusV1TO $updated_status updatedStatus (required)
	 * @param  string $x_api_key (optional)
	 * @param  string $x_app_api_key (optional)
	 * @param  string $accept_language (optional)
	 *
	 * @throws \Swagger\Client\ApiException on non-2xx response
	 * @throws \InvalidArgumentException
	 * @return array of \Swagger\Client\Model\API1SingleResultResponseStatusV1TO_, HTTP status code, HTTP response headers (array of strings)
	 */
	public function updateOneUsingPUTWithHttpInfo( $id, $updated_status, $x_api_key = null, $x_app_api_key = null, $accept_language = null ) {
		$returnType = '\Swagger\Client\Model\API1SingleResultResponseStatusV1TO_';
		$request    = $this->updateOneUsingPUTRequest( $id, $updated_status, $x_api_key, $x_app_api_key, $accept_language );

		try {
			$options = $this->createHttpClientOption();
			try {
				$response = $this->client->send( $request, $options );
			} catch ( RequestException $e ) {
				throw new ApiException(
					"[{$e->getCode()}] {$e->getMessage()}",
					$e->getCode(),
					$e->getResponse() ? $e->getResponse()->getHeaders() : null,
					$e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
				);
			}

			$statusCode = $response->getStatusCode();

			if ( $statusCode < 200 || $statusCode > 299 ) {
				throw new ApiException(
					sprintf(
						'[%d] Error connecting to the API (%s)',
						$statusCode,
						$request->getUri()
					),
					$statusCode,
					$response->getHeaders(),
					$response->getBody()
				);
			}

			$responseBody = $response->getBody();
			if ( $returnType === '\SplFileObject' ) {
				$content = $responseBody; //stream goes to serializer
			} else {
				$content = $responseBody->getContents();
				if ( $returnType !== 'string' ) {
					$content = json_decode( $content );
				}
			}

			return [
				ObjectSerializer::deserialize( $content, $returnType, [] ),
				$response->getStatusCode(),
				$response->getHeaders(),
			];

		} catch ( ApiException $e ) {
			switch ( $e->getCode() ) {
				case 200:
					$data = ObjectSerializer::deserialize(
						$e->getResponseBody(),
						'\Swagger\Client\Model\API1SingleResultResponseStatusV1TO_',
						$e->getResponseHeaders()
					);
					$e->setResponseObject( $data );
					break;
			}
			throw $e;
		}
	}

	/**
	 * Operation updateOneUsingPUTAsync
	 *
	 * Update one Status
	 *
	 * @param  int $id id (required)
	 * @param  \Swagger\Client\Model\StatusV1TO $updated_status updatedStatus (required)
	 * @param  string $x_api_key (optional)
	 * @param  string $x_app_api_key (optional)
	 * @param  string $accept_language (optional)
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function updateOneUsingPUTAsync( $id, $updated_status, $x_api_key = null, $x_app_api_key = null, $accept_language = null ) {
		return $this->updateOneUsingPUTAsyncWithHttpInfo( $id, $updated_status, $x_api_key, $x_app_api_key, $accept_language )
			->then(
				function ( $response ) {
					return $response[0];
				}
			);
	}

	/**
	 * Operation updateOneUsingPUTAsyncWithHttpInfo
	 *
	 * Update one Status
	 *
	 * @param  int $id id (required)
	 * @param  \Swagger\Client\Model\StatusV1TO $updated_status updatedStatus (required)
	 * @param  string $x_api_key (optional)
	 * @param  string $x_app_api_key (optional)
	 * @param  string $accept_language (optional)
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Promise\PromiseInterface
	 */
	public function updateOneUsingPUTAsyncWithHttpInfo( $id, $updated_status, $x_api_key = null, $x_app_api_key = null, $accept_language = null ) {
		$returnType = '\Swagger\Client\Model\API1SingleResultResponseStatusV1TO_';
		$request    = $this->updateOneUsingPUTRequest( $id, $updated_status, $x_api_key, $x_app_api_key, $accept_language );

		return $this->client
			->sendAsync( $request, $this->createHttpClientOption() )
			->then(
				function ( $response ) use ( $returnType ) {
					$responseBody = $response->getBody();
					if ( $returnType === '\SplFileObject' ) {
						$content = $responseBody; //stream goes to serializer
					} else {
						$content = $responseBody->getContents();
						if ( $returnType !== 'string' ) {
							$content = json_decode( $content );
						}
					}

					return [
						ObjectSerializer::deserialize( $content, $returnType, [] ),
						$response->getStatusCode(),
						$response->getHeaders(),
					];
				},
				function ( $exception ) {
					$response   = $exception->getResponse();
					$statusCode = $response->getStatusCode();
					throw new ApiException(
						sprintf(
							'[%d] Error connecting to the API (%s)',
							$statusCode,
							$exception->getRequest()->getUri()
						),
						$statusCode,
						$response->getHeaders(),
						$response->getBody()
					);
				}
			);
	}

	/**
	 * Create request for operation 'updateOneUsingPUT'
	 *
	 * @param  int $id id (required)
	 * @param  \Swagger\Client\Model\StatusV1TO $updated_status updatedStatus (required)
	 * @param  string $x_api_key (optional)
	 * @param  string $x_app_api_key (optional)
	 * @param  string $accept_language (optional)
	 *
	 * @throws \InvalidArgumentException
	 * @return \GuzzleHttp\Psr7\Request
	 */
	protected function updateOneUsingPUTRequest( $id, $updated_status, $x_api_key = null, $x_app_api_key = null, $accept_language = null ) {
		// verify the required parameter 'id' is set
		if ( $id === null ) {
			throw new \InvalidArgumentException(
				'Missing the required parameter $id when calling updateOneUsingPUT'
			);
		}
		// verify the required parameter 'updated_status' is set
		if ( $updated_status === null ) {
			throw new \InvalidArgumentException(
				'Missing the required parameter $updated_status when calling updateOneUsingPUT'
			);
		}

		$resourcePath = '/1/status/{id}';
		$formParams   = [];
		$queryParams  = [];
		$headerParams = [];
		$httpBody     = '';
		$multipart    = false;

		// header params
		if ( $x_api_key !== null ) {
			$headerParams['x-api-key'] = ObjectSerializer::toHeaderValue( $x_api_key );
		}
		// header params
		if ( $x_app_api_key !== null ) {
			$headerParams['x-app-api-key'] = ObjectSerializer::toHeaderValue( $x_app_api_key );
		}
		// header params
		if ( $accept_language !== null ) {
			$headerParams['Accept-Language'] = ObjectSerializer::toHeaderValue( $accept_language );
		}

		// path params
		if ( $id !== null ) {
			$resourcePath = str_replace(
				'{' . 'id' . '}',
				ObjectSerializer::toPathValue( $id ),
				$resourcePath
			);
		}

		// body params
		$_tempBody = null;
		if ( isset( $updated_status ) ) {
			$_tempBody = $updated_status;
		}

		if ( $multipart ) {
			$headers = $this->headerSelector->selectHeadersForMultipart(
				[ '*/*' ]
			);
		} else {
			$headers = $this->headerSelector->selectHeaders(
				[ '*/*' ],
				[ 'application/json' ]
			);
		}

		// for model (json/xml)
		if ( isset( $_tempBody ) ) {
			// $_tempBody is the method argument, if present
			$httpBody = $_tempBody;
			// \stdClass has no __toString(), so we should encode it manually
			if ( $httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json' ) {
				$httpBody = \GuzzleHttp\json_encode( $httpBody );
			}
		} elseif ( count( $formParams ) > 0 ) {
			if ( $multipart ) {
				$multipartContents = [];
				foreach ( $formParams as $formParamName => $formParamValue ) {
					$multipartContents[] = [
						'name'     => $formParamName,
						'contents' => $formParamValue,
					];
				}
				// for HTTP post (form)
				$httpBody = new MultipartStream( $multipartContents );

			} elseif ( $headers['Content-Type'] === 'application/json' ) {
				$httpBody = \GuzzleHttp\json_encode( $formParams );

			} else {
				// for HTTP post (form)
				$httpBody = \GuzzleHttp\Psr7\build_query( $formParams );
			}
		}

		$defaultHeaders = [];
		if ( $this->config->getUserAgent() ) {
			$defaultHeaders['User-Agent'] = $this->config->getUserAgent();
		}

		$headers = array_merge(
			$defaultHeaders,
			$headerParams,
			$headers
		);

		$query = \GuzzleHttp\Psr7\build_query( $queryParams );
		return new Request(
			'PUT',
			$this->config->getHost() . $resourcePath . ( $query ? "?{$query}" : '' ),
			$headers,
			$httpBody
		);
	}

	/**
	 * Create http client option
	 *
	 * @throws \RuntimeException on file opening failure
	 * @return array of http client options
	 */
	protected function createHttpClientOption() {
		$options = [];
		if ( $this->config->getDebug() ) {
			$options[ RequestOptions::DEBUG ] = fopen( $this->config->getDebugFile(), 'a' );
			if ( ! $options[ RequestOptions::DEBUG ] ) {
				throw new \RuntimeException( 'Failed to open the debug file: ' . $this->config->getDebugFile() );
			}
		}

		return $options;
	}
}
